"""Default constants and thresholds for Mnemlet."""

# Token limits
MAX_CHUNK_TOKENS = 3000
MAX_RECALL_TOKENS = 2000

# Dedup threshold (cosine similarity)
DEDUP_THRESHOLD = 0.95

# Default decay parameters
# Exponential decay rate (higher = faster forgetting). Halbwertszeit ≈ ln(2)/λ.
DEFAULT_LAMBDA = 0.01
DEFAULT_PURGE_THRESHOLD = 0.05
DEFAULT_HARD_DELETE_THRESHOLD = 0.01
DEFAULT_HARD_DELETE_AGE_DAYS = 90

# Interaction boost values
BOOST_CREATE = 0.10
BOOST_RECALL = 0.15
BOOST_UPDATE = 0.20
BOOST_REFERENCE = 0.08
PENALTY_IGNORE = -0.02

# Retrieval defaults
DEFAULT_TOP_N = 5
MAX_TOP_N = 10
HYBRID_BM25_WEIGHT = 0.3
HYBRID_VECTOR_WEIGHT = 0.7

# API
API_PREFIX = "/api/v1"

# System namespaces
SYSTEM_NAMESPACE = "__system__"
SHARED_NAMESPACE = "shared"

# Intelligence memory types
MEMORY_TYPE_FACT = "fact"
MEMORY_TYPE_PREFERENCE = "preference"
MEMORY_TYPE_INSTRUCTION = "instruction"
MEMORY_TYPE_EVENT = "event"
MEMORY_TYPE_CONTEXT = "context"
MEMORY_TYPES = (
    MEMORY_TYPE_FACT,
    MEMORY_TYPE_PREFERENCE,
    MEMORY_TYPE_INSTRUCTION,
    MEMORY_TYPE_EVENT,
    MEMORY_TYPE_CONTEXT,
)

# Intelligence memory statuses
MEMORY_STATUS_ACTIVE = "active"
MEMORY_STATUS_COLD_STORAGE = "cold_storage"
MEMORY_STATUS_DELETED = "deleted"
MEMORY_STATUS_SUPERSEDED = "superseded"
MEMORY_STATUS_FORGOTTEN = "forgotten"
MEMORY_STATUSES = (
    MEMORY_STATUS_ACTIVE,
    MEMORY_STATUS_COLD_STORAGE,
    MEMORY_STATUS_DELETED,
    MEMORY_STATUS_SUPERSEDED,
    MEMORY_STATUS_FORGOTTEN,
)

# Context Pack thresholds
CONTEXT_PRIMARY_SCORE_THRESHOLD = 0.70
CONTEXT_SUPPORTING_SCORE_THRESHOLD = 0.30
CONTRADICTION_AUTO_SUPERSEDE_THRESHOLD = 0.80

# Review commands
BOOST_CONFIRM = 0.20
